-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-11-11 13:36:43 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE brdg_cast_film (
    ncosnt       VARCHAR(10 ) NOT NULL,
    tconst       VARCHAR(10 ) NOT NULL,
    insert_date  TIMESTAMP NOT NULL,
    update_date  TIMESTAMP
);

ALTER TABLE brdg_cast_film MODIFY COLUMN ncosnt  VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the name/person';

ALTER TABLE brdg_cast_film MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the title';

ALTER TABLE brdg_cast_film MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE brdg_cast_film MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE brdg_cast_film ADD CONSTRAINT brdg_cast_film_pk PRIMARY KEY ( ncosnt,
                                                                          tconst );

CREATE TABLE brdg_cast_profession (
    ncosnt         VARCHAR(10 ) NOT NULL,
    id_profession  INTEGER NOT NULL,
    insert_date    TIMESTAMP NOT NULL,
    update_date    TIMESTAMP
);

ALTER TABLE brdg_cast_profession MODIFY COLUMN ncosnt VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the name/person';

ALTER TABLE brdg_cast_profession MODIFY COLUMN id_profession INTEGER COMMENT
    'id profession inherited from catalogue';

ALTER TABLE brdg_cast_profession MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE brdg_cast_profession MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE brdg_cast_profession ADD CONSTRAINT brdg_cast_profession_pk PRIMARY KEY ( ncosnt,
                                                                                      id_profession );

CREATE TABLE brdg_film_gnr (
    tconst       VARCHAR(10 ) NOT NULL,
    id_genre     INTEGER NOT NULL,
    insert_date TIMESTAMP NOT NULL,
    update_date  TIMESTAMP
);

ALTER TABLE brdg_film_gnr MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the title';

ALTER TABLE brdg_film_gnr MODIFY COLUMN id_genre INTEGER COMMENT
    'id genre code inherited from catalogue';

ALTER TABLE brdg_film_gnr MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE brdg_film_gnr MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE brdg_film_gnr ADD CONSTRAINT brdg_film_gnr_pk PRIMARY KEY ( tconst,
                                                                        id_genre );

CREATE TABLE cast (
    ncosnt       VARCHAR(10 ) NOT NULL,
    primaryname  VARCHAR(150 ) NOT NULL,
    birthyear    DATE,
    deathyear    DATE,
    insert_date TIMESTAMP NOT NULL,
    update_date  TIMESTAMP
);

ALTER TABLE cast MODIFY COLUMN ncosnt VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the name/person';

ALTER TABLE cast MODIFY COLUMN primaryname VARCHAR(150 ) COMMENT
    'name by which the person COMMENT most often credited';

ALTER TABLE cast MODIFY COLUMN birthyear DATE COMMENT
    'in YYYY format';

ALTER TABLE cast MODIFY COLUMN deathyear  DATE COMMENT
    'in YYYY format if applicable, else ''\N''';

ALTER TABLE cast MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cast MODIFY COLUMN update_date  TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cast ADD CONSTRAINT cast_pk PRIMARY KEY ( ncosnt );

CREATE TABLE cat_aka_type (
    id_aka_type    INTEGER NOT NULL,
    desc_aka_type  VARCHAR(30 ) NOT NULL,
    insert_date    TIMESTAMP NOT NULL,
    update_date    TIMESTAMP
);

ALTER TABLE cat_aka_type MODIFY COLUMN id_aka_type INTEGER COMMENT
    'id aka type';

ALTER TABLE cat_aka_type MODIFY COLUMN desc_aka_type VARCHAR(30 ) COMMENT
    'Enumerated set of attributes for this alternative title. One or more of the following: "alternative", "dvd", "festival", "tv", "video", "working", "original", "imdbDisplay". New values may be added in the future without warning';

ALTER TABLE cat_aka_type MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cat_aka_type MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cat_aka_type ADD CONSTRAINT cat_aka_type_pk PRIMARY KEY ( id_aka_type );

CREATE TABLE cat_category (
    id_category    INTEGER NOT NULL,
    desc_category  VARCHAR(40 ) NOT NULL,
    insert_date    TIMESTAMP NOT NULL,
    update_date    TIMESTAMP
);

ALTER TABLE cat_category MODIFY COLUMN id_category INTEGER COMMENT
    'id category';

ALTER TABLE cat_category MODIFY COLUMN desc_category VARCHAR(40 ) COMMENT
    'Category Desc';

ALTER TABLE cat_category MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cat_category MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cat_category ADD CONSTRAINT cat_category_pk PRIMARY KEY ( id_category );

CREATE TABLE cat_country (
    id_country    INTEGER NOT NULL,
    code_alpha2   VARCHAR(2 ) NOT NULL,
    code_alpha3   VARCHAR(3 ),
    country_name  VARCHAR(30 ),
    region        VARCHAR(25 ),
    population    DECIMAL(18, 2),
    insert_date   TIMESTAMP NOT NULL,
    update_date   TIMESTAMP
);

ALTER TABLE cat_country MODIFY COLUMN id_country INTEGER COMMENT
    'id country ';

ALTER TABLE cat_country MODIFY COLUMN code_alpha2 VARCHAR(2 ) COMMENT
    'the region for this version of the title';

ALTER TABLE cat_country MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cat_country MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cat_country ADD CONSTRAINT cat_country_pk PRIMARY KEY ( id_country );

CREATE TABLE cat_genre (
    id_genre     INTEGER NOT NULL,
    desc_genre   VARCHAR(40 ) NOT NULL,
    insert_date TIMESTAMP NOT NULL,
    update_date  TIMESTAMP
);

ALTER TABLE cat_genre MODIFY COLUMN id_genre INTEGER COMMENT
    'id genre';

ALTER TABLE cat_genre MODIFY COLUMN desc_genre VARCHAR(40 ) COMMENT
    'includes up to three genres associated with the title';

ALTER TABLE cat_genre MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cat_genre MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cat_genre ADD CONSTRAINT cat_genre_pk PRIMARY KEY ( id_genre );

CREATE TABLE cat_language (
    id_language    INTEGER NOT NULL,
    desc_language  VARCHAR(30 ) NOT NULL,
    insert_date    TIMESTAMP NOT NULL,
    update_date    TIMESTAMP
);

ALTER TABLE cat_language MODIFY COLUMN id_language INTEGER COMMENT
    'id language';

ALTER TABLE cat_language MODIFY COLUMN desc_language VARCHAR(30 ) COMMENT
    'the language of the title';

ALTER TABLE cat_language MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cat_language MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cat_language ADD CONSTRAINT cat_language_pk PRIMARY KEY ( id_language );

CREATE TABLE cat_profession (
    id_profession    INTEGER NOT NULL,
    desc_profession  VARCHAR(50 ) NOT NULL,
    insert_date      TIMESTAMP NOT NULL,
    update_date      TIMESTAMP
);

ALTER TABLE cat_profession ADD CONSTRAINT cat_profession_pk PRIMARY KEY ( id_profession );

CREATE TABLE cat_type (
    id_type      INTEGER NOT NULL,
    desc_type    VARCHAR(20 ) NOT NULL,
    insert_date TIMESTAMP NOT NULL,
    update_date  TIMESTAMP
);

ALTER TABLE cat_type MODIFY COLUMN id_type INTEGER COMMENT
    'id type from category';

ALTER TABLE cat_type MODIFY COLUMN desc_type VARCHAR(20 ) COMMENT
    'the type/format of the title (e.g. movie, short, tvseries, tvepisode, video, etc)';

ALTER TABLE cat_type MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE cat_type MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE cat_type ADD CONSTRAINT cat_type_pk PRIMARY KEY ( id_type );

CREATE TABLE episode (
    tconst         VARCHAR(10 ) NOT NULL,
    parenttconst   VARCHAR(10 ) NOT NULL,
    seasonnumber   INTEGER NOT NULL,
    episodenumber  INTEGER NOT NULL,
    insert_date    TIMESTAMP NOT NULL,
    update_date    TIMESTAMP
);

ALTER TABLE episode MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'alphanumeric identifier of episode';

ALTER TABLE episode MODIFY COLUMN parenttconst VARCHAR(10 ) COMMENT
    'alphanumeric identifier of the parent TV Series';

ALTER TABLE episode MODIFY COLUMN seasonnumber INTEGER COMMENT
    'season number the episode belongs to';

ALTER TABLE episode MODIFY COLUMN episodenumber INTEGER COMMENT
    'episode number of the tconst in the TV series';

ALTER TABLE episode MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE episode MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE episode ADD CONSTRAINT episode_pk PRIMARY KEY ( tconst );

CREATE TABLE film (
    tconst          VARCHAR(10 ) NOT NULL,
    primarytitle    VARCHAR(430 ) NOT NULL,
    originaltitle   VARCHAR(430 ),
    id_type         INTEGER NOT NULL,
    isadult         CHAR(1),
    startyear       DATE,
    endyear         DATE,
    runtimeminutes  INTEGER NOT NULL,
    insert_date     TIMESTAMP NOT NULL,
    update_date     TIMESTAMP
);

ALTER TABLE film MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'a tconst, an alphanumeric unique identifier of the title';

ALTER TABLE film MODIFY COLUMN primarytitle VARCHAR(430 )COMMENT
    'the more popular title / the title used by the filmmakers on promotional materials at the point of release';

ALTER TABLE film MODIFY COLUMN originaltitle VARCHAR(430 ) COMMENT
    'original title, in the original language';

ALTER TABLE film MODIFY COLUMN id_type INTEGER COMMENT
    'id type inherited  from catalogue';

ALTER TABLE film MODIFY COLUMN isadult CHAR(1) COMMENT
    '0: non-adult title; 1: adult title';

ALTER TABLE film MODIFY COLUMN startyear DATE COMMENT
    'represents the release year of a title. In the case of TV Series, it COMMENT the series start year';

ALTER TABLE film MODIFY COLUMN endyear DATE COMMENT
    'TV Series end year. ‘\N’ for all other title types';

ALTER TABLE film MODIFY COLUMN runtimeminutes INTEGER COMMENT
    'primary runtime of the title, in minutes';

ALTER TABLE film MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE film MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

CREATE UNIQUE INDEX film__idx ON
    film (
        id_type
    ASC );

ALTER TABLE film ADD CONSTRAINT film_pk PRIMARY KEY ( tconst );

CREATE TABLE film_aka (
    tconst           VARCHAR(10 ) NOT NULL,
    ordering         INTEGER NOT NULL,
    title_name       VARCHAR(450 ),
    id_country       INTEGER NOT NULL,
    id_language      INTEGER NOT NULL,
    id_aka_type      INTEGER NOT NULL,
    attributes       VARCHAR(70 ),
    isoriginaltitle  CHAR(1),
    insert_date      TIMESTAMP NOT NULL,
    update_date      TIMESTAMP
);

ALTER TABLE film_aka MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the title';

ALTER TABLE film_aka MODIFY COLUMN ordering INTEGER COMMENT
    'a number to uniquely identify rows for a given titleId';

ALTER TABLE film_aka MODIFY COLUMN title_name VARCHAR(450 ) COMMENT
    'the localized title';

ALTER TABLE film_aka MODIFY COLUMN id_country INTEGER COMMENT
    'id country inherited from catalogue';

ALTER TABLE film_aka MODIFY COLUMN id_language INTEGER COMMENT
    'id language  inherited from catalogue';

ALTER TABLE film_aka MODIFY COLUMN id_aka_type INTEGER COMMENT
    'id aka  type  inherited from catalogue';

ALTER TABLE film_aka MODIFY COLUMN attributes VARCHAR(70 ) COMMENT
    'Additional terms to describe this alternative title, not enumerated';

ALTER TABLE film_aka MODIFY COLUMN isoriginaltitle CHAR(1) COMMENT
    '0: not original title; 1: original title';

ALTER TABLE film_aka MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE film_aka MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

CREATE UNIQUE INDEX film_aka__idx ON
    film_aka (
        id_aka_type
    ASC );

ALTER TABLE film_aka ADD CONSTRAINT film_aka_pk PRIMARY KEY ( ordering,
                                                              tconst );

CREATE TABLE principal (
    tconst       VARCHAR(10 ) NOT NULL,
    ordering     INTEGER NOT NULL,
    ncosnt       VARCHAR(10 ) NOT NULL,
    id_category  INTEGER NOT NULL,
    desc_job     VARCHAR(150 ) NOT NULL,
    characters    VARCHAR(150 ),
    insert_date TIMESTAMP NOT NULL,
    update_date  TIMESTAMP
);

ALTER TABLE principal MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the title';

ALTER TABLE principal MODIFY COLUMN ordering INTEGER COMMENT
    'a number to uniquely identify rows for a given titleId';

ALTER TABLE principal MODIFY COLUMN ncosnt VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the name/person';

ALTER TABLE principal MODIFY COLUMN id_category INTEGER COMMENT
    'id category inherited from catalogue';

ALTER TABLE principal MODIFY COLUMN desc_job VARCHAR(150 ) COMMENT
    ' the specific job title if applicable, else ''\N''';

ALTER TABLE principal MODIFY COLUMN characters VARCHAR(150 ) COMMENT
    'the name of the character played if applicable, else ''\N''';

ALTER TABLE principal MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE principal MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

CREATE UNIQUE INDEX principal__idx ON
    principal (
        ncosnt
    ASC );

ALTER TABLE principal
    ADD CONSTRAINT principal_pk PRIMARY KEY ( tconst,
                                              ordering,
                                              ncosnt );

CREATE TABLE rating (
    tconst         VARCHAR(10 ) NOT NULL,
    averagerating  INTEGER NOT NULL,
    numvotes       INTEGER NOT NULL,
    insert_date    TIMESTAMP NOT NULL,
    update_date    TIMESTAMP
);

ALTER TABLE rating MODIFY COLUMN tconst VARCHAR(10 ) COMMENT
    'alphanumeric unique identifier of the title';

ALTER TABLE rating MODIFY COLUMN averagerating INTEGER COMMENT
    'weighted average of all the individual user ratings';

ALTER TABLE rating MODIFY COLUMN numvotes INTEGER COMMENT
    'number of votes the title has received';

ALTER TABLE rating MODIFY COLUMN insert_date TIMESTAMP COMMENT
    'Date when data was populated in the table';

ALTER TABLE rating MODIFY COLUMN update_date TIMESTAMP COMMENT
    'Date when data was updated in the table';

ALTER TABLE rating ADD CONSTRAINT rating_pk PRIMARY KEY ( tconst );

ALTER TABLE brdg_cast_profession
    ADD CONSTRAINT brdg_cast_cat_profession_fk FOREIGN KEY ( id_profession )
        REFERENCES cat_profession ( id_profession );

ALTER TABLE brdg_film_gnr
    ADD CONSTRAINT brdg_film_gnr_cat_genre_fk FOREIGN KEY ( id_genre )
        REFERENCES cat_genre ( id_genre );

ALTER TABLE episode
    ADD CONSTRAINT episode_episode_fk FOREIGN KEY ( parenttconst )
        REFERENCES episode ( tconst );

ALTER TABLE episode
    ADD CONSTRAINT episode_film_fk FOREIGN KEY ( tconst )
        REFERENCES film ( tconst );

ALTER TABLE film_aka
    ADD CONSTRAINT film_aka_cat_aka_type_fk FOREIGN KEY ( id_aka_type )
        REFERENCES cat_aka_type ( id_aka_type );

ALTER TABLE film_aka
    ADD CONSTRAINT film_aka_cat_country_fk FOREIGN KEY ( id_country )
        REFERENCES cat_country ( id_country );

ALTER TABLE film_aka
    ADD CONSTRAINT film_aka_cat_language_fk FOREIGN KEY ( id_language )
        REFERENCES cat_language ( id_language );

ALTER TABLE film_aka
    ADD CONSTRAINT film_aka_film_fk FOREIGN KEY ( tconst )
        REFERENCES film ( tconst );

ALTER TABLE film
    ADD CONSTRAINT film_cat_type_fk FOREIGN KEY ( id_type )
        REFERENCES cat_type ( id_type );

ALTER TABLE principal
    ADD CONSTRAINT principal_cast_fk FOREIGN KEY ( ncosnt )
        REFERENCES cast ( ncosnt );

ALTER TABLE principal
    ADD CONSTRAINT principal_cat_category_fk FOREIGN KEY ( id_category )
        REFERENCES cat_category ( id_category );

ALTER TABLE principal
    ADD CONSTRAINT principal_film_fk FOREIGN KEY ( tconst )
        REFERENCES film ( tconst );

ALTER TABLE rating
    ADD CONSTRAINT rating_film_fk FOREIGN KEY ( tconst )
        REFERENCES film ( tconst );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             3
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
